import 'package:karabookapp/common/app_resources.dart';
import 'package:karabookapp/pages/portfolio/data/models/achievements.dart';

class C {
  static const vip = 'Vip';
  static const gift = 'Gift';

  static final achievementsLocalData = <Achievements>[
    const Achievements(
      icon: AppResources.silver,
      title: "SILVER STAR",
      counter: 5,
      subTitle: "PICTURES DONE",
      category: "PICTURES DONE",
      progress: 0.0,
      current: 0,
    ),
    const Achievements(
      icon: AppResources.gold,
      title: "GOLDEN STAR",
      counter: 10,
      current: 0,
      subTitle: "PICTURES DONE",
      category: "PICTURES DONE",
      progress: 0.0,
    ),
    const Achievements(
      icon: AppResources.platinum,
      title: "PLATINUM STAR",
      counter: 15,
      current: 0,
      subTitle: "PICTURES DONE",
      category: "PICTURES DONE",
      progress: 0.0,
    ),
    const Achievements(
      icon: AppResources.diamond,
      title: "DIAMOND STAR",
      counter: 20,
      current: 0,
      subTitle: "PICTURES DONE",
      category: "PICTURES DONE",
      progress: 0.0,
    ),
    const Achievements(
      icon: AppResources.food,
      title: "FOOD FAN",
      counter: 5,
      current: 0,
      subTitle: "PICS IN FOOD",
      category: "FOOD",
      progress: 0.0,
    ),
    const Achievements(
      icon: AppResources.nature,
      title: "NATURE LOVER",
      counter: 5,
      current: 0,
      subTitle: "PICS IN NATURE",
      category: "NATURE",
      progress: 0.0,
    ),
    const Achievements(
      icon: AppResources.people,
      title: "GREAT PERSONALITY",
      counter: 5,
      current: 0,
      subTitle: "IN PEOPLE",
      category: "PEOPLE",
      progress: 0.0,
    ),
    const Achievements(
      icon: AppResources.fauna,
      title: "FAUNA ADMIRER ",
      counter: 5,
      current: 0,
      subTitle: "IN ANIMALS & BIRDS",
      category: "ANIMALS & BIRDS",
      progress: 0.0,
    ),
    const Achievements(
      icon: AppResources.mandala,
      title: "RELAX LOVER",
      counter: 5,
      current: 0,
      subTitle: "IN MANDALAS",
      category: "MANDALAS",
      progress: 0.0,
    ),
    const Achievements(
      icon: AppResources.transport,
      title: "SPEED LOVER",
      counter: 5,
      current: 0,
      subTitle: "IN CARS & TRANSPORT",
      category: "CARS & TRANSPORT",
      progress: 0.0,
    ),
    const Achievements(
      icon: AppResources.fantasy,
      title: "INSPIRE OTHERS",
      counter: 5,
      current: 0,
      subTitle: "IN FANTASY",
      category: "FANTASY",
      progress: 0.0,
    ),
    const Achievements(
      icon: AppResources.design,
      title: "CREATOR",
      counter: 5,
      current: 0,
      subTitle: "IN DESIGN",
      category: "DESIGN",
      progress: 0.0,
    ),
    const Achievements(
      icon: AppResources.flowers,
      title: "REAL BEAUTY",
      counter: 5,
      current: 0,
      subTitle: "IN FLOWERS",
      category: "FLOWERS",
      progress: 0.0,
    ),
    const Achievements(
      icon: AppResources.butterfly,
      title: "AMAZING CREATIONS LOVER",
      counter: 5,
      current: 0,
      subTitle: "IN BUTTERFLIES",
      category: "BUTTERFLIES",
      progress: 0.0,
    ),
    const Achievements(
      icon: AppResources.cities,
      title: "EXPLORER",
      counter: 5,
      current: 0,
      subTitle: "IN CITIES",
      category: "CITIES",
      progress: 0.0,
    ),
    const Achievements(
      icon: AppResources.vip,
      title: "YOU ARE SIMPLY THE BEST",
      counter: 5,
      current: 0,
      subTitle: "IN VIP",
      category: "VIP",
      progress: 0.0,
    ),
  ];
}
