name: karabookapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2


  #LOCALIZATION
  easy_localization: ^3.0.3

  #STATE MANAGER
  flutter_bloc: ^8.1.3
  shared_preferences: ^2.2.2

  #IMAGE
  lottie: ^3.0.0
  flutter_svg: ^2.0.9
  flutter_screenutil: ^5.9.0
  percent_indicator: ^4.2.3

  #SERVICES
  auto_route: ^7.8.4
  fluttertoast: ^8.2.4
  equatable: ^2.0.5
  either_dart: ^1.0.0

  #EXAMPLE
  hexcolor: ^3.0.1
  path_drawing: ^1.0.1

dev_dependencies:
  auto_route_generator: ^7.3.2
  build_runner: ^2.4.8

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/locale/
    - assets/images/
    - assets/lottie/
    - assets/icons/
    - assets/icons/achievements/

  fonts:
   - family: Nunito
     fonts:
       - asset: assets/fonts/Nunito-Regular.ttf

